<a href="https://colab.research.google.com/github/ryanpropst1/99partDux/blob/master/Python_DataAnalytics_Course_Chegg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
store_state = ["TN","KY". "GA", "AL" ]

SyntaxError: invalid syntax (<ipython-input-2-7e41d2072c53>, line 1)

In [ ]:
store_state = ["TN","KY","GA","AL"]

print(store_state[0])

store_state.append("FL")

store_state.insert(0,"NC")

print(store_state[0:])

store_state.reverse()

print(store_state)

store_state.append("WI")

store_state.sort()

print(store_state)





TN
['NC', 'TN', 'KY', 'GA', 'AL', 'FL']
['FL', 'AL', 'GA', 'KY', 'TN', 'NC']


In [ ]:
store_state = ["TN","KY","GA","AL"]

print(store_state[0])

store_state.append("FL")

store_state.insert(0,"NC")

print(store_state[0:])

store_state.reverse()

print(store_state)

store_state.append("WI")

store_state.sort(reverse=True)

print(store_state)

store_state.sort()

print(store_state)

store_state.remove("AL")

print(store_state)

store_state.count("FL")


TN
['NC', 'TN', 'KY', 'GA', 'AL', 'FL']
['FL', 'AL', 'GA', 'KY', 'TN', 'NC']
['WI', 'TN', 'NC', 'KY', 'GA', 'FL', 'AL']
['AL', 'FL', 'GA', 'KY', 'NC', 'TN', 'WI']
['FL', 'GA', 'KY', 'NC', 'TN', 'WI']


1

In [ ]:
employee_info = {'last_name':"AJ", 'emp_id':19620329, 'dept':'grocery', 'employment_length':4}

employee_info.update({'location':"St. Petersberg"})

print(employee_info)

print(employee_info['last_name'])

employee_info.update({'Level':"Manager"})

#print(employee_info)

del employee_info['dept']
print(employee_info)

# dictionary_name.clear()

print(employee_info.get('location'))

emp_id_severance = employee_info.pop('emp_id')

print(emp_id_severance)
print(employee_info)



{'last_name': 'AJ', 'emp_id': 19620329, 'dept': 'grocery', 'employment_length': 4, 'location': 'St. Petersberg'}
AJ
{'last_name': 'AJ', 'emp_id': 19620329, 'employment_length': 4, 'location': 'St. Petersberg', 'Level': 'Manager'}
St. Petersberg
19620329
{'last_name': 'AJ', 'employment_length': 4, 'location': 'St. Petersberg', 'Level': 'Manager'}


In [ ]:
emp_years = [3,5,2,1,11,1,2,10]

for emp_benefit_level in emp_years:
  if emp_benefit_level < 2:
    continue
    print(emp_benefit_level)

In [ ]:
#Python For Loop

emp_yrs = [3,7,2,1,0,1,2,10]

#for new_var in squence_var
#perform task using new_var

#for emp_bene_level in emp_yrs:
  #print(emp_bene_level)

for emp_bene_level in emp_yrs:
  if emp_bene_level < 2:
    continue
    print(emp_bene_level)

for emp_bene_level in emp_yrs:
 #print(f"(emp_bene_level) is the employee who has worked here less than a year." )
 print(emp_bene_level)
 if emp_bene_level == 0:
    break


3
7
2
1
0


In [ ]:
fruit_inventory = ['apples', 'pears', 'cherries', 'grapes', 'kiwis']

for fruit in fruit_inventory:

  if fruit == 'pears' or fruit == 'kiwis':

    print(fruit)

pears
kiwis


In [ ]:

day_apps = [3, 4, 7, 5, 3, 5, 0, 4, 2, 5, 6, 7, 4, 2]

# While Loops

# Assign and initialize variables

week_apps_sum = 0
week_days = 0  # Loop counter

while week_days <7: # Loop Condition & Conditional Code flow logic#
  print("Index position:", week_days, "Day App Data:", day_apps[week_days], "Iterating Sum:", week_apps_sum)
  week_apps_sum = week_apps_sum + day_apps[week_days]
  week_days += 1

print (week_apps_sum)

week_apps_sum = 0
week_days = 7  # Loop counter

while week_days <14: # Loop Condition & Conditional Code flow logic#
  print("Index position:", week_days, "Day App Data:", day_apps[week_days], "Iterating Sum:", week_apps_sum)
  week_apps_sum = week_apps_sum + day_apps[week_days]
  week_days += 1

print (week_apps_sum)




department_numbers = [234, 574, 489, 297, 351, 732, 931]

item_count = 0

while item_count <5:

  print(department_numbers[item_count])

  item_count += 1

Index position: 0 Day App Data: 3 Iterating Sum: 0
Index position: 1 Day App Data: 4 Iterating Sum: 3
Index position: 2 Day App Data: 7 Iterating Sum: 7
Index position: 3 Day App Data: 5 Iterating Sum: 14
Index position: 4 Day App Data: 3 Iterating Sum: 19
Index position: 5 Day App Data: 5 Iterating Sum: 22
Index position: 6 Day App Data: 0 Iterating Sum: 27
27
Index position: 7 Day App Data: 4 Iterating Sum: 0
Index position: 8 Day App Data: 2 Iterating Sum: 4
Index position: 9 Day App Data: 5 Iterating Sum: 6
Index position: 10 Day App Data: 6 Iterating Sum: 11
Index position: 11 Day App Data: 7 Iterating Sum: 17
Index position: 12 Day App Data: 4 Iterating Sum: 24
Index position: 13 Day App Data: 2 Iterating Sum: 28
30
234
574
489
297
351


In [ ]:
day_apps = [3, 4, 7, 5, 3, 5, 0, 4, 2, 5, 6, 7, 4, 2]


week_apps_sum = 0
week_days = 0

while week_days <=13:
  print("Index position:", week_days, "Day App Data:", day_apps[week_days], "Iterating Sum:", week_apps_sum)
  week_apps_sum = week_apps_sum + day_apps [week_days]
  if week_apps_sum >= 50:
    break
  week_days += 1


print (week_apps_sum)


num_days = 0
week_days = 0

while week_days <7:

  if day_apps[week_days] <5:
    week_days += 1
    continue

  num_days += 1
  week_days += 1

print (num_days)

Index position: 0 Day App Data: 3 Iterating Sum: 0
Index position: 1 Day App Data: 4 Iterating Sum: 3
Index position: 2 Day App Data: 7 Iterating Sum: 7
Index position: 3 Day App Data: 5 Iterating Sum: 14
Index position: 4 Day App Data: 3 Iterating Sum: 19
Index position: 5 Day App Data: 5 Iterating Sum: 22
Index position: 6 Day App Data: 0 Iterating Sum: 27
Index position: 7 Day App Data: 4 Iterating Sum: 27
Index position: 8 Day App Data: 2 Iterating Sum: 31
Index position: 9 Day App Data: 5 Iterating Sum: 33
Index position: 10 Day App Data: 6 Iterating Sum: 38
Index position: 11 Day App Data: 7 Iterating Sum: 44
51
3


In [ ]:
#pip list

#pip install emoji

#import matplotlib as mpl
import numpy as np
#import pandas as pd
#import seaborn as sns
#import sqlalchemy as sa

import numpy
numpy.random.random()
print(numpy.random.random())

import numpy as np
np.random.random()
print(np.random.random())

import numpy.random as np
np.random()
print(np.random())






0.1888250095859716
0.1186246690781444
0.26876923061791014


In [ ]:
import matplotlib as mpl
import numpy as np
import pandas as pd
import seaborn as sns
import sqlalchemy as sa


training_hours = np.array([3, 4, 2, 5, 29, 1, 5])

num_products = [[3, 5, 8, 9, 12],[5, 1, 3, 14, 7]]


import numpy as np
prod_sales_array = np.array([5, 8, 3, 7, 10])
print (prod_sales_array)

import numpy as np
prod_sales_array_2 = np.array([[5, 8, 3, 7, 10], [7, 3, 5, 12, 9], [4, 11, 10, 2, 14]])
print (prod_sales_array_2)

np.ndim(prod_sales_array_2)
print(np.ndim(prod_sales_array_2))

np.shape(prod_sales_array_2)
print(np.shape(prod_sales_array_2))

np.size(prod_sales_array_2)
print(np.size(prod_sales_array_2))

print(prod_sales_array_2.dtype)











[ 5  8  3  7 10]
[[ 5  8  3  7 10]
 [ 7  3  5 12  9]
 [ 4 11 10  2 14]]
2
(3, 5)
15
int64
